apiVersion: v1
kind: Secret
metadata:
  name: api-keys
data:
  openai-api-key: {{ .Values.key.openai_api_key | b64enc}}
  discord-api-key:  {{ .Values.key.discord_api_key | b64enc}}
  discord-pub-key: {{ .Values.key.discord_pub_key | b64enc}}

