apiVersion: v1
kind: Secret
metadata:
  name: api-keys
data:
  openai_api_key: {{ .Values.key.openai_api_key | b64enc}}
  discord_api_key:  {{ .Values.key.discord_api_key | b64enc}}
  discord_pub_key: {{ .Values.key.discord_pub_key | b64enc}}

