apiVersion: v1
kind: Secret
metadata:
  name: api-keys
data:
  openai-api-key: {{ .Values.key.openai-api-key | b64enc}}
  discord-api-key:  {{ .Values.key.discord-api-key | b64enc}}
  discord-pub-key: {{ .Values.key.discord-pub-key | b64enc}}

